name: Gitartwork
on:
  push:
  pull_request:
  schedule:
    - cron: "0 */12 * * *" # Runs on the 0, 6, 12 and 18th hour.
  workflow_dispatch:
jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jasineri/gitartwork@v1
        with:
          user_name: ${{ github.repository_owner }}
          text: M.HIEU!
      - name: Move gitartwork.svg to dist
        run: mv gitartwork.svg dist/
      - name: Push animations to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
