name: Grid snake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 */12 * * *" # Runs on the 0, 6, 12 and 18th hour.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3.1.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/grid-snake.svg
            dist/grid-snake-dark.svg?palette=github-dark
        env:
          # a GitHub token is required to fetch the contribution calendar from GitHub API
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push animations to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
